### ISSUE TITLE
Support pug templates

### ISSUE THREAD

**Issue by IlyaSemenov** [HJinPeng/vite-plugin-vue-css-module#2]
This works:

```vue
<template>
  <div cls="tabs">test</div>
</template>

<style module lang="sass">
.tabs
  color: red
</style>
```

it generates: `<div class="_tabs_116b1_1">test</div>`

but this doesn't work:

```vue
<template lang="pug">
div(cls="tabs") test
</template>

<style module lang="sass">
.tabs
  color: red
</style>
```

The `cls` attribute is not processed and it generates: `<div cls="tabs">test</div>`

Can you please support pug? I believe it should be doable, as the similar project https://github.com/zeokku/vite-plugin-vue-css-modules works with pug just fine.

**Comment by HJinPeng** [comment]
Thanks for your use and comment, the pug template may be supported in v1.2.* version, and you will be notified at that time @IlyaSemenov

**Comment by HJinPeng** [comment]
Hello, pug is already supported. You can use it in version ^1.2.1. Looking forward to your use and feedback. @IlyaSemenov

**Comment by IlyaSemenov** [comment]
I confirm that it works, thanks!

To be honest, ideally I'd like an option to intercept pug's [class literals](https://pugjs.org/language/attributes.html#class-literal). This is opinionated, so it should be disabled by default, but what would be ideal for me is:

```ts
vueCssModule({
  attrName: 'cls',
  processPugClassLiterals: true, // false by default
}), 
```

```vue
<template lang="pug">
div(cls="hello") This is always bold
div(class="hello") This is never bold
.hello This is bold if processPugClassLiterals is enabled
</template>

<style module>
.hello {
  font-weight: bold;
}
</style>
```

**Comment by HJinPeng** [comment]
Thanks for your feedback!
As for syntactic sugar, I think it is an extension of the class attribute, and the function of the class attribute and the grammatical features of pug should still be retained.
Considering that sometimes global class names are used in .vue files that use cssModule, it makes sense for both class and cls to exist at the same time, and the practice of changing the original attributes is easy to confuse. So the plugin hopes to still maintain the role of the class in any case.

**Comment by IlyaSemenov** [comment]
I agree, that's why I specifically pointed that `class="hello"` should keep its role regardless of the plugin. However, the class literal syntax is **not** class attribute. Pug just happens to translate `.hello` to `<div class="hello">`, but these are different grammar constructs.

Another way to look at this would be as follows: mental transition from `<div class="hello">` (uses global CSS) to `<div cls="hello"` (or `<div module-class="hello">`, as I prefer) which uses module css is clear and concise. But unfortunately there is no counterpart transition from pug's `.foo Content` to ...what? I'm trying to invent one. I was thinking some syntax like `.module:foo Content` but that's disregarded by Pug. Hence my suggestion was to enable direct class literal (not class attribute) transition, but since that indeed could be confusing it should be disabled by default. Perhaps you have better ideas?
