### ISSUE TITLE
Breaks on sub-templates in Vite 5

### ISSUE THREAD

**Issue by IlyaSemenov** [HJinPeng/vite-plugin-vue-css-module#6]
The following code fails to compile with Nuxt 3.11 / vite-plugin-vue-css-module 2:

```vue
<template lang="pug">
template foo
</template>

<style module>
.foo {
  color: red;
}
</style>
```

with error:

```
 ERROR  Nuxt Build Error: [vite:vue] [plugin vite:vue] app.vue (1:46): Invalid end tag.
file: /home/projects/nuxt-starter-g8exf9/app.vue:1:46
```

Minimal reproduction: https://stackblitz.com/edit/nuxt-starter-g8exf9

Run:

```sh
npm run build
```

This used to work with Nuxt 3.8, and it also works without `vite-plugin-vue-css-module`, so the problem is in how `vite-plugin-vue-css-module` handles Vite 5.

**Comment by IlyaSemenov** [comment]
@shijinyu since you were adding Vite 5 support, can you also take a look?

**Comment by IlyaSemenov** [comment]
I think I found it. This code is gone in the latest release:

https://github.com/HJinPeng/vite-plugin-vue-css-module/blob/97118d2d3ef51e8ea50449c29aceb9a0c89190e1/src/index.ts#L34-L39

So the code above becomes:

```vue
<template lang="pug">
  <template>foo</template>
</template>
```

which is not what vue compiler is happy with (it works fine without `lang="pug"` though, so it used to work in the previous `vite-plugin-vue-css-module` release).

**Comment by IlyaSemenov** [comment]
I traced the problem to that you're using `vue/compiler-sfc#parse`:

https://github.com/HJinPeng/vite-plugin-vue-css-module/blob/d8354ae88b5aed1b53d3ca239059fcb98c4e7ec5/src/utils/parseVue.ts#L1

which doesn't return the full template (or SFC) AST but only creates AST for the template children:

https://github.com/vuejs/core/blob/01172fdb777f9a0b51781ed2015a1ba3824340a3/packages/compiler-sfc/src/parse.ts#L186

```ts
    switch (node.tag) {
      case 'template':
        if (!descriptor.template) {
          const templateBlock = (descriptor.template = createBlock(
            node,
            source,
            false,
          ) as SFCTemplateBlock)

          if (!templateBlock.attrs.src) {
            templateBlock.ast = createRoot(node.children, source) // <------ here
          }
```

To get the full AST (to discover the location of the `lang` attribute) we'll probably need to call `CompilerDOM.parse` ourselves, similarly how Vue does that:

https://github.com/vuejs/core/blob/01172fdb777f9a0b51781ed2015a1ba3824340a3/packages/compiler-sfc/src/parse.ts#L154-L155

```ts
  const ast = compiler.parse(source, {
    parseMode: 'sfc',
```

---

Question however, why do we need to convert pug to HTML in this plugin? Can't we just update the actual pug source? That will eliminate the need to patch the "outside" `<template>` tag and generally streamline the flow.

**Comment by HJinPeng** [comment]
I have received your issue and PR. I will verify it as soon as possible. Thank you so much.

**Comment by IlyaSemenov** [comment]
@HJinPeng Thank you. The major problem now is that HMR not working, but I think it's better if the rest is merged before I can proceed with that problem.
